# Generated by Django 4.1.6 on 2023-02-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_name_song_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='albums_id',
        ),
    ]
